<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>niml</string>
	</array>
	<key>name</key>
	<string>Niml</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.jinja</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tagblock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#stylusblock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#cssblock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sassblock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#cocoblock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#coffeeblock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#jsblock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#plainblock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#jinjablock</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attrib</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attrib_string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attrib_noquote</string>
				</dict>
			</array>
		</dict>
		<key>attrib_noquote</key>
		<dict>
			<key>begin</key>
			<string>(\w[-$:\w]*=)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.niml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(\s|$))</string>
			<key>name</key>
			<string>string.double-quote.niml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.jinja</string>
				</dict>
			</array>
		</dict>
		<key>attrib_string</key>
		<dict>
			<key>begin</key>
			<string>(\w[-$:\w]*=)(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.niml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\2</string>
			<key>name</key>
			<string>string.double-quote.niml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.jinja</string>
				</dict>
			</array>
		</dict>
		<key>brackets</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>support.other.niml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>class</key>
		<dict>
			<key>begin</key>
			<string>\.</string>
			<key>comment</key>
			<string>Class Names</string>
			<key>end</key>
			<string>(?=[^-:\w\$])</string>
			<key>name</key>
			<string>storage.type.niml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
			</array>
		</dict>
		<key>cocoblock</key>
		<dict>
			<key>begin</key>
			<string>(\s*)(:)(coco)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.niml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.niml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s+|\s*$))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.coco</string>
				</dict>
			</array>
		</dict>
		<key>coffeeblock</key>
		<dict>
			<key>begin</key>
			<string>(\s*)(:)(coffee(script)?)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.niml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.niml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s+|\s*$))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.coffee</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>#\s+.*$</string>
			<key>name</key>
			<string>comment.line.niml</string>
		</dict>
		<key>cssblock</key>
		<dict>
			<key>begin</key>
			<string>(\s*)(:)(s?css)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.niml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.niml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s+|\s*$))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.scss</string>
				</dict>
			</array>
		</dict>
		<key>dotvar</key>
		<dict>
			<key>begin</key>
			<string>(\.[a-zA-Z_][a-zA-Z0-9_]*)+(?=(\(|\[)?)</string>
			<key>end</key>
			<string>(?=(\.(?![a-zA-Z0-9_])|[^\(\[\.]))</string>
			<key>name</key>
			<string>support.other.niml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#paren</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dotvar</string>
				</dict>
			</array>
		</dict>
		<key>escape</key>
		<dict>
			<key>comment</key>
			<string>An escape</string>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>keyword.source.niml</string>
		</dict>
		<key>escaped_char</key>
		<dict>
			<key>match</key>
			<string>\\x[0-9A-F]{2}</string>
			<key>name</key>
			<string>constant.character.escape.hex.jinja</string>
		</dict>
		<key>escaped_unicode_char</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.unicode.16-bit-hex.jinja</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.unicode.32-bit-hex.jinja</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.unicode.name.jinja</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\U[0-9A-Fa-f]{8})|(\\u[0-9A-Fa-f]{4})|(\\N\{[a-zA-Z ]+\})</string>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.niml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.niml.block</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*\b(block)\s+([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.niml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.niml.filter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*\b(filter)\s+([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.niml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=%-|%)\s*\b([a-zA-Z_][a-zA-Z0-9_]*)\b(?!\s*[,=])</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.niml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.niml.test</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*\b(is)\s+([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(and|else|if|in|import|not|or|recursive|with(out)?\s+context)\b</string>
					<key>name</key>
					<string>keyword.control.niml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false|none)\b</string>
					<key>name</key>
					<string>constant.language.niml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(loop|super|self|varargs|kwargs)\b</string>
					<key>name</key>
					<string>variable.language.niml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_][a-zA-Z0-9_]*</string>
					<key>name</key>
					<string>variable.other.niml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\+|\-|\*\*|\*|//|/|%)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.niml</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.niml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.niml.filter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\|)([a-zA-Z_][a-zA-Z0-9_]*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.niml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.niml.attribute</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.)([a-zA-Z_][a-zA-Z0-9_]*)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.niml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.niml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.other.niml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(\.|:|\||,)</string>
					<key>name</key>
					<string>punctuation.other.niml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(==|&amp;lt;=|=&amp;gt;|&amp;lt;|&amp;gt;|!=)</string>
					<key>name</key>
					<string>keyword.operator.comparison.niml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.operator.assignment.niml</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.niml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.niml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.niml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.niml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.niml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.niml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>@/</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.regexp.begin.niml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.regexp.end.niml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.niml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#simple_escapes</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>id</key>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>comment</key>
			<string>Class Names</string>
			<key>end</key>
			<string>(?=[^-:\w\$])</string>
			<key>name</key>
			<string>keyword.source.niml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
			</array>
		</dict>
		<key>jinjablock</key>
		<dict>
			<key>begin</key>
			<string>^\s*%</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>support.other.niml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>jsblock</key>
		<dict>
			<key>begin</key>
			<string>(\s*)(:)(javascript)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.niml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.niml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s+|\s*$))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>paren</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>support.other.niml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#paren</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>plainblock</key>
		<dict>
			<key>begin</key>
			<string>(\s*)(:)(plain)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.niml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.niml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s+|\s*$))</string>
			<key>patterns</key>
			<array>
			</array>
		</dict>
		<key>sassblock</key>
		<dict>
			<key>begin</key>
			<string>(\s*)(:)(s[ca]ss)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.niml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.niml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s+|\s*$))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sass</string>
				</dict>
			</array>
		</dict>
		<key>simple_escapes</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.newline.niml</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.tab.niml</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.vertical-tab.niml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.backlash.niml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.double-quote.niml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.single-quote.niml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.bell.niml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.backspace.niml</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.formfeed.niml</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.linefeed.niml</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.return.niml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\\n)|(\\\\)|(\\\")|(\\')|(\\a)|(\\b)|(\\f)|(\\n)|(\\r)|(\\t)|(\\v)</string>
		</dict>
		<key>singleprop</key>
		<dict>
			<key>begin</key>
			<string>\\</string>
			<key>comment</key>
			<string>A single property like selected or multiple</string>
			<key>end</key>
			<string>(?=[^-:\w\$])</string>
			<key>name</key>
			<string>storage.type.niml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#simple_escapes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped_unicode_char</string>
				</dict>
			</array>
		</dict>
		<key>stylusblock</key>
		<dict>
			<key>begin</key>
			<string>(\s*)(:)(stylus)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.niml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.niml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s+|\s*$))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.stylus</string>
				</dict>
			</array>
		</dict>
		<key>tag</key>
		<dict>
			<key>comment</key>
			<string>Tag Name</string>
			<key>match</key>
			<string>@/?[-$:\w]+</string>
			<key>name</key>
			<string>entity.niml</string>
		</dict>
		<key>tagblock</key>
		<dict>
			<key>begin</key>
			<string>((@/?[\w:-]+)|(\.[-:\w]+)|(#[-:\w]+))</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.niml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.niml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.source.niml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\s*(\.[-:\$\w]+|#[-:\$\w]+|[-\$:\w]+=|\\[-\$:\w]+))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#id</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attrib</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singleprop</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>begin</key>
			<string>\$[a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z_][a-zA-Z0-9_]*)*(?=(\(|\[)?)</string>
			<key>end</key>
			<string>(?=(\.(?![a-zA-Z0-9_])|[^\(\[\.]))</string>
			<key>name</key>
			<string>support.other.niml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#paren</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dotvar</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.niml</string>
	<key>uuid</key>
	<string>3814d5f3-a8c7-4590-89cc-b9e343b7aef6</string>
</dict>
</plist>
